# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Branch: ${{ github.event.inputs.branch }}"
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Deploy to minikube
      run:
        kubectl apply -f depl.yaml
    - name: Interact with the cluster
      run: kubectl get pods
    - name: Interact with the cluster
      run: |
        kubectl get pods
        kubectl get service   
